#!/bin/sh

# 设置 mdev 作为热插拔事件管理器
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s && echo "mdev is ok......"  # 初始化设备节点并输出确认信息

# 创建控制台和空设备节点（对于 NFS 根文件系统而言）
#mknod -m 600 /dev/console c 5 1  # 创建控制台设备节点，权限为 600
#mknod -m 666 /dev/null c 1 3     # 创建空设备节点，权限为 666

# 设置全局环境变量
export PATH=/bin:/sbin:/usr/bin:/usr/sbin  # 定义基本路径变量
export PATH=/system/bin:$PATH             # 添加 /system/bin 到路径中
export LD_LIBRARY_PATH=/system/lib        # 指定动态链接库搜索路径

# 网络配置
ifconfig lo up                           # 启动本地回环网络接口
#ifconfig eth0 192.168.1.80              # 配置以太网接口 IP 地址（被注释掉了）
                                         #注意再同一个子网

# 启动 telnet 守护进程
telnetd &                                # 在后台运行 telnet 服务

# 从硬件时钟设置系统时间
#hwclock -s                              # 设置系统时间为硬件时钟的时间（被注释掉了）

# 增加 RTSP 发送编码缓冲区大小
sysctl -w net.core.wmem_max=26214400     # 设置最大发送缓冲区大小
sysctl -w net.core.wmem_default=26214400 # 设置默认发送缓冲区大小

# 挂载系统分区
mount -t jffs2 /dev/mtdblock3 /system    # 将 JFFS2 文件系统的第 3 个 MTD 块设备挂载到 /system

# 如果系统分区无效，则格式化系统分区
if [ ! -f /system/.system ]; then        # 检查是否存在 .system 文件来判断是否需要初始化
    echo "Format system partition..."    # 输出提示信息
    umount -f /system                    # 强制卸载系统分区
    flash_eraseall /dev/mtd3             # 擦除第 3 个 MTD 分区的所有内容
    mount -t jffs2 /dev/mtdblock3 /system  # 重新挂载系统分区
    cd /system                            # 进入系统目录
    mkdir -p bin init etc/sensor lib/firmware lib/modules  # 创建必要的子目录
    echo "#!/bin/sh" > init/app_init.sh  # 创建初始脚本文件
    chmod 755 init/app_init.sh           # 修改初始脚本文件权限为可执行
    touch .system                         # 创建标记文件，表示系统已经初始化
    cd /                                  # 返回根目录
    echo "Done"                          # 输出完成信息
fi

# 执行系统初始化脚本
if [ -f /system/init/app_init.sh ]; then  # 检查初始化脚本是否存在
    /system/init/app_init.sh &            # 在后台运行初始化脚本
fi

















